name: Test

on
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  job1:
    name: Do test run
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
    - uses: actions/checkout@v2

    - name: Use Node.js
    - uses: actions/setup-node@v1

    - name: Test run
      run: |
        cd
      working-directory: ./docs
      